version: "3.3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  web:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - mongo
    volumes:
      - .:/src
    environment:
      - DATABASE_URL=mongodb://mongo/beers
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - web
    links:
      - mongo

volumes:
  mongodb:
